In [1]:
import numpy as np
import pandas as pd

In [ ]:
#dataframe using list in dictionary
d={
    'Name':["rajib","Anna","Peter","linda"],
    'Age':[20,34,54,42],
    'City':['Berlin','Paris','London','NewYork'],
    'Salary':[6500,70000,62000,850000]
}
pd.DataFrame(d)

    Name  Age     City  Salary
0  rajib   20   Berlin    6500
1   Anna   34    Paris   70000
2  Peter   54   London   62000
3  linda   42  NewYork  850000

In [38]:
#DAta frame with list of dictionary
list=[
    {"name":"Rajib","Age":20,"City":"Gorkha","Salary":45000},
    {"name":"jib","Age":23,"City":"Kathmandu","Salary":55000},
    {"name":"Raj","Age":24,"City":"Chitwan","Salary":60000}
]
df=pd.DataFrame(list)
df

    name  Age       City  Salary
0  Rajib   20     Gorkha   45000
1    jib   23  Kathmandu   55000
2    Raj   24    Chitwan   60000

In [21]:
#Selecting one column
df['name']

0    Rajib
1      jib
2      Raj
Name: name, dtype: object

In [30]:
#selecting double column
#df['name','Age'] #wrong
df[['name','Age']]

    name  Age
0  Rajib   20
1    jib   23
2    Raj   24

In [32]:
#Creating a new Column
df['roll']=[1,2,3]
df

    name       City  Salary  roll
0  Rajib     Gorkha   45000     1
1    jib  Kathmandu   55000     2
2    Raj    Chitwan   60000     3

In [ ]:
#Remove a column#
#df.drop("name of the column",axis=1#for column and 0 for row)
df=df.drop(columns="Age",inplace=True)
df

    name       City  Salary
0  Rajib     Gorkha   45000
1    jib  Kathmandu   55000
2    Raj    Chitwan   60000

In [36]:
#Selecting row using iloc for default index 
df.loc[[1,2]]

  name       City  Salary  roll
1  jib  Kathmandu   55000     2
2  Raj    Chitwan   60000     3

In [37]:
df.iloc[2]

name          Raj
City      Chitwan
Salary      60000
roll            3
Name: 2, dtype: object

In [39]:
#selecting subset of column and row
df

    name  Age       City  Salary
0  Rajib   20     Gorkha   45000
1    jib   23  Kathmandu   55000
2    Raj   24    Chitwan   60000

In [41]:
df.loc[[1,2]][["name","Age"]]

  name  Age
1  jib   23
2  Raj   24

In [46]:
df[df["Age"]>21]

  name  Age       City  Salary
1  jib   23  Kathmandu   55000
2  Raj   24    Chitwan   60000

In [54]:
#double condtion
df[(df["Age"]>21) & (df["City"]=="Chitwan")]

  name  Age     City  Salary
2  Raj   24  Chitwan   60000