**Merging**

In [6]:
import pandas as pd

df1 = pd.DataFrame({
    'EmployeeID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'Finance', 'IT', 'Marketing']
})


df2 = pd.DataFrame({
    'EmployeeID': [102, 103, 104, 105],
    'Salary': [50000, 60000, 55000, 45000]
})
print(df1)
print(df2)

   EmployeeID     Name Department
0         101    Alice         HR
1         102      Bob    Finance
2         103  Charlie         IT
3         104    David  Marketing
   EmployeeID  Salary
0         102   50000
1         103   60000
2         104   55000
3         105   45000

**default Merge**

In [2]:
pd.merge(df1,df2)

   EmployeeID     Name Department  Salary
0         102      Bob    Finance   50000
1         103  Charlie         IT   60000
2         104    David  Marketing   55000

**Merge with on**

In [3]:
pd.merge(df1,df2,on='EmployeeID')

   EmployeeID     Name Department  Salary
0         102      Bob    Finance   50000
1         103  Charlie         IT   60000
2         104    David  Marketing   55000

**Merge with how**

In [4]:
pd.merge(df1,df2,how='outer')

   EmployeeID     Name Department   Salary
0         101    Alice         HR      NaN
1         102      Bob    Finance  50000.0
2         103  Charlie         IT  60000.0
3         104    David  Marketing  55000.0
4         105      NaN        NaN  45000.0

In [5]:
pd.merge(df1,df2,how='left')

   EmployeeID     Name Department   Salary
0         101    Alice         HR      NaN
1         102      Bob    Finance  50000.0
2         103  Charlie         IT  60000.0
3         104    David  Marketing  55000.0

In [7]:
pd.merge(df1,df2,how='right')

   EmployeeID     Name Department  Salary
0         102      Bob    Finance   50000
1         103  Charlie         IT   60000
2         104    David  Marketing   55000
3         105      NaN        NaN   45000

## concatenate

In [9]:
pd.concat([df1,df2])

   EmployeeID     Name Department   Salary
0         101    Alice         HR      NaN
1         102      Bob    Finance      NaN
2         103  Charlie         IT      NaN
3         104    David  Marketing      NaN
0         102      NaN        NaN  50000.0
1         103      NaN        NaN  60000.0
2         104      NaN        NaN  55000.0
3         105      NaN        NaN  45000.0

In [10]:
pd.concat([df1,df2],axis=1)

   EmployeeID     Name Department  EmployeeID  Salary
0         101    Alice         HR         102   50000
1         102      Bob    Finance         103   60000
2         103  Charlie         IT         104   55000
3         104    David  Marketing         105   45000

## Joining

In [18]:

df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'Finance', 'IT', 'Marketing']
}, index=[101, 102, 103, 104])


df2 = pd.DataFrame({
    'Salary': [50000, 60000, 55000, 45000]
}, index=[102, 103, 104, 105])

In [19]:
df1

        Name Department
101    Alice         HR
102      Bob    Finance
103  Charlie         IT
104    David  Marketing

In [20]:
df2

     Salary
102   50000
103   60000
104   55000
105   45000

In [21]:
df1.join(df2)

        Name Department   Salary
101    Alice         HR      NaN
102      Bob    Finance  50000.0
103  Charlie         IT  60000.0
104    David  Marketing  55000.0

In [22]:
df2.join(df1)

     Salary     Name Department
102   50000      Bob    Finance
103   60000  Charlie         IT
104   55000    David  Marketing
105   45000      NaN        NaN

In [23]:
df1.join(df2,how='outer')

        Name Department   Salary
101    Alice         HR      NaN
102      Bob    Finance  50000.0
103  Charlie         IT  60000.0
104    David  Marketing  55000.0
105      NaN        NaN  45000.0

In [27]:
df2.join(df1,how='right')

      Salary     Name Department
101      NaN    Alice         HR
102  50000.0      Bob    Finance
103  60000.0  Charlie         IT
104  55000.0    David  Marketing