In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
# import kagglehub

# Download latest version
# path = kagglehub.dataset_download("susant4learning/holiday-package-purchase-prediction")

# print("Path to dataset files:", path)

In [4]:
df=pd.read_csv('Travel.csv')

In [5]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

## Handling missing values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [7]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [8]:
df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [9]:
df['Age']=df['Age'].fillna(int(df['Age'].mean()))
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,37.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [10]:
df['TypeofContact']=df['TypeofContact'].fillna('Self Enquiry')

In [11]:
df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                           0
TypeofContact                 0
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [12]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [13]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3469
Company Invited    1419
Name: count, dtype: int64

In [14]:
df['DurationOfPitch']=df['DurationOfPitch'].fillna(df['DurationOfPitch'].mean())

In [15]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [16]:
import numpy as np

# Syntax: np.where(condition, value_if_true, value_if_false)
df['Gender'] = np.where(df['Gender'] == 'Fe Male', 'Female', df['Gender'])

In [17]:
df['Occupation'].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4888 non-null   float64
 3   TypeofContact             4888 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4888 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [19]:
df['ProductPitched'].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [20]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [21]:
df['MaritalStatus']=np.where(df['MaritalStatus']=='Unmarried','Single',df['MaritalStatus'])

In [22]:
df['Designation'].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [23]:
df.isna().sum()

CustomerID                    0
ProdTaken                     0
Age                           0
TypeofContact                 0
CityTier                      0
DurationOfPitch               0
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [24]:
df['NumberOfFollowups'].value_counts()

NumberOfFollowups
4.0    2068
3.0    1466
5.0     768
2.0     229
1.0     176
6.0     136
Name: count, dtype: int64

In [25]:
# The [0] converts the Series into a single value
df['NumberOfFollowups'] = df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].mode()[0])

In [26]:
df['PreferredPropertyStar'].value_counts()

PreferredPropertyStar
3.0    2993
5.0     956
4.0     913
Name: count, dtype: int64

In [27]:
df['MonthlyIncome']=df['MonthlyIncome'].fillna(df['MonthlyIncome'].mean())

In [28]:
df['PreferredPropertyStar']=df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mean())

In [29]:
df['NumberOfChildrenVisiting']=df['NumberOfTrips'].fillna(df['NumberOfTrips'].mode()[0])
df['NumberOfChildrenVisiting']=df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].mode()[0])

In [30]:
df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'],axis=1,inplace=True)
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'Designation', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object')

In [31]:
x=df.drop(columns=['ProdTaken'],axis=1)
y=df['ProdTaken']

In [32]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=42)

In [33]:
xtrain

,CustomerID,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
4128,204128,31.0,Self Enquiry,1,10.000000,Large Business,Female,4.0,Basic,5.0,Single,7.0,1,4,0,Executive,21335.000000,10.0
1157,201157,37.0,Company Invited,1,14.000000,Salaried,Female,3.0,Deluxe,3.0,Married,2.0,0,5,1,Manager,23619.853491,4.0
744,200744,37.0,Self Enquiry,1,15.490835,Small Business,Female,5.0,Deluxe,4.0,Divorced,6.0,0,4,1,Manager,19777.000000,9.0
4753,204753,43.0,Self Enquiry,3,11.000000,Small Business,Male,4.0,Deluxe,5.0,Single,2.0,0,5,1,Manager,23833.000000,5.0
2312,202312,28.0,Self Enquiry,1,18.000000,Salaried,Female,3.0,Basic,3.0,Married,2.0,1,4,1,Executive,17515.000000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,204426,28.0,Self Enquiry,1,10.000000,Small Business,Male,5.0,Basic,3.0,Single,2.0,0,1,1,Executive,20723.000000,5.0
466,200466,41.0,Self Enquiry,3,8.000000,Salaried,Female,3.0,Super Deluxe,5.0,Divorced,1.0,0,5,1,AVP,31595.000000,4.0
3092,203092,38.0,Company Invited,3,28.000000,Small Business,Female,4.0,Basic,3.0,Divorced,7.0,0,2,1,Executive,21651.000000,10.0
3772,203772,28.0,Self Enquiry,3,30.000000,Small Business,Female,5.0,Deluxe,3.0,Married,3.0,0,1,1,Manager,22218.000000,6.0
860,200860,22.0,Company Invited,1,9.000000,Salaried,Male,4.0,Basic,3.0,Divorced,1.0,1,3,0,Executive,17853.000000,3.0

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
cat_feature=x.select_dtypes(include="object").columns
num_feature=x.select_dtypes(exclude='object').columns
num_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

In [35]:
cat_feature

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')

In [36]:
preprocessor=ColumnTransformer([
    ("OneHotEncoder",oh_transformer,cat_feature),
    ("StandardScaler",num_transformer,num_feature)]
)

In [37]:
xtrain=preprocessor.fit_transform(xtrain)
xtest=preprocessor.transform(xtest)

In [38]:
xtrain

array([[ 1.        ,  1.        ,  0.        , ..., -1.27370232,
        -0.42799594,  1.86107258],
       [ 0.        ,  0.        ,  1.        , ...,  0.7851128 ,
         0.0055776 , -1.00520332],
       [ 1.        ,  0.        ,  0.        , ...,  0.7851128 ,
        -0.72364184,  1.38335993],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.7851128 ,
        -0.36803181,  1.86107258],
       [ 1.        ,  0.        ,  0.        , ...,  0.7851128 ,
        -0.26043796, -0.04977802],
       [ 0.        ,  0.        ,  1.        , ..., -1.27370232,
        -1.08873987, -1.48291598]])

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score,f1_score,roc_auc_score,roc_curve

In [40]:
models={
    "Random Forest":RandomForestClassifier(n_estimators= 100, min_samples_split= 2, min_samples_leaf= 1, max_features='sqrt', max_depth= 30)
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(xtrain,ytrain)
    ytrain_pred=model.predict(xtrain)
    ytest_pred=model.predict(xtest)

    modeltrain_accuracy=accuracy_score(ytrain_pred,ytrain)
    modeltrain_f1=f1_score(ytrain,ytrain_pred)
    modeltrain_precision=precision_score(ytrain,ytrain_pred)
    modeltrain_recall=recall_score(ytrain,ytrain_pred)
    modeltrain_rocauc_score=roc_auc_score(ytrain,ytrain_pred)


    modeltest_accuracy=accuracy_score(ytest_pred,ytest)
    modeltest_f1=f1_score(ytest,ytest_pred)
    modeltest_precision=precision_score(ytest,ytest_pred)
    modeltest_recall=recall_score(ytest,ytest_pred)
    modeltest_rocauc_score=roc_auc_score(ytest,ytest_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print('- Accuracy: {:.4f}'.format(modeltrain_accuracy))
    print('- F1 score: {:.4f}'.format(modeltrain_f1))

    print('- Precision: {:.4f}'.format(modeltrain_precision))
    print('- Recall: {:.4f}'.format(modeltrain_recall))
    print('- Roc Auc Score: {:.4f}'.format(modeltrain_rocauc_score))

    print('-----------------------------------')

    print('Model performance for Test set')
    print('- Accuracy: {:.4f}'.format(modeltest_accuracy))
    print('- F1 score: {:.4f}'.format(modeltest_f1))
    print('- Precision: {:.4f}'.format(modeltest_precision))
    print('- Recall: {:.4f}'.format(modeltest_recall))
    print('- Roc Auc Score: {:.4f}'.format(modeltest_rocauc_score))

    print('='*35)
    print('\n')

Random Forest
Model performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- Roc Auc Score: 1.0000
-----------------------------------
Model performance for Test set
- Accuracy: 0.9214
- F1 score: 0.7348
- Precision: 0.9568
- Recall: 0.5964
- Roc Auc Score: 0.7952
===================================

In [41]:
#Hyper parameter tunning
param_rf = {
    'n_estimators': [100, 200, 500],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

In [42]:
from sklearn.model_selection import RandomizedSearchCV

models_rcv=[
    ("rf" ,RandomForestClassifier(),param_rf)
]

In [43]:
from sklearn.model_selection import RandomizedSearchCV

# 1. Initialize the dictionary OUTSIDE the loop
model_results = {}

for name, model, params in models_rcv:
    print(f"Starting tuning for: {name}...")
    
    random = RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        cv=3,
        verbose=1, # Reduced verbose slightly to keep console cleaner
        n_iter=100,
        n_jobs=-1,
        random_state=42 # Added for reproducibility
    )
    
    random.fit(xtrain, ytrain)
    
    # 2. Store more than just params (Best Params + Best Score)
    model_results[name] = {
        'params': random.best_params_,
        'score': random.best_score_,
        'best_model': random.best_estimator_
    }

# 3. Printing the results
for model_name, results in model_results.items():
    print(f"\n{'='*20} {model_name} {'='*20}")
    print(f"Best Score: {results['score']:.4f}")
    print(f"Best Params: {results['params']}")

Starting tuning for: rf...
Fitting 3 folds for each of 100 candidates, totalling 300 fits

==================== rf ====================
Best Score: 0.8969
Best Params: {'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': None}