In [1]:
import pandas as pd
list=[1,2,3,4]
series=pd.Series(list)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
#create a series from dictionaries 
dic={"name":"RAjib","roll":23053748}
seriesd=pd.Series(dic)
print(seriesd)

name       RAjib
roll    23053748
dtype: object

In [4]:
#Creating series from with indexes
indexes=[1,2,3]
data=["rajib","ranjan","jaiswal"]
seriesI=pd.Series(data=data,index=indexes)
print(seriesI)

1      rajib
2     ranjan
3    jaiswal
dtype: object

In [5]:
#DataFrame
#creating data from dictionary lists
d_list={
    "name":["rajib","ranjan","jaiswal"],
    "age":[23,21,22],
    "City":["Delhi","Mumbai","Ranchi"]
}
df = pd.DataFrame(d_list)
print(df)

      name  age    City
0    rajib   23   Delhi
1   ranjan   21  Mumbai
2  jaiswal   22  Ranchi

In [6]:
#creating dataframes from list of dictionaries
list = [
    {"name":"RAjib","age":45},
    {"name":"raj","age":43},
    {"name":"rabi","age":23}
        ]

df = pd.DataFrame(list)
print(df)

    name  age
0  RAjib   45
1    raj   43
2   rabi   23

In [8]:
df

    name  age
0  RAjib   45
1    raj   43
2   rabi   23

### Acessing Data in a DataFrame

In [10]:
#For specific column
df['name']
type(df['name'])

pandas.core.series.Series

In [11]:
#selecting the row
df.loc[0]

name    RAjib
age        45
Name: 0, dtype: object

In [12]:
#selecting one element
df.loc[0][0]

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_13624\3869893977.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'RAjib'

In [14]:
#acessing data from default index
df.iloc[0]

df.iloc[0][0]

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_13624\1413928523.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'RAjib'

In [16]:
#Acessing data using at function
print(df.at[1,'age']) #selecting 1 row of age column

43

### Data Manipulation with Pandas

In [22]:
df['salary']=[50000,60000,70000]
df

    name  age  salary
0  RAjib   45   50000
1    raj   43   60000
2   rabi   23   70000

In [23]:
df.drop('salary' ,axis=1 ,inplace=True)
df

    name  age
0  RAjib   45
1    raj   43
2   rabi   23

In [26]:
df['age']=df['age']-1
df

    name  age
0  RAjib   20
1    raj   18
2   rabi   -2

In [27]:
df.describe()

             age
count   3.000000
mean   12.000000
std    12.165525
min    -2.000000
25%     8.000000
50%    18.000000
75%    19.000000
max    20.000000