In [2]:
import pandas as pd
df=pd.read_csv('ee.csv')
df.head(5)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50.0
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50.0
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10.0
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20.0
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20.0

In [3]:
df.tail(5)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
45,136,Hazel,NaN,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50.0
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50.0
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,NaN,50.0
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50.0
49,140,NaN,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50.0

In [4]:
df.describe()

       EMPLOYEE_ID  DEPARTMENT_ID
count    50.000000      48.000000
mean    134.760000      57.083333
std      33.631594      25.176681
min     100.000000      10.000000
25%     112.250000      50.000000
50%     124.500000      50.000000
75%     136.750000      60.000000
max     206.000000     110.000000

In [5]:
df.dtypes

EMPLOYEE_ID         int64
FIRST_NAME         object
LAST_NAME          object
EMAIL              object
PHONE_NUMBER       object
HIRE_DATE          object
JOB_ID             object
SALARY             object
COMMISSION_PCT     object
MANAGER_ID         object
DEPARTMENT_ID     float64
dtype: object

In [6]:
df.isnull()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,True,True,False,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,True,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,True,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False
32,False,False,True,False,False,False,False,False,False,False,True
33,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False
45,False,False,True,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,True,False
48,False,False,False,False,False,False,False,False,False,False,False
49,False,True,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45     True
46    False
47     True
48    False
49     True
dtype: bool

In [8]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        2
LAST_NAME         4
EMAIL             0
PHONE_NUMBER      1
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        1
DEPARTMENT_ID     2
dtype: int64

In [9]:
df.fillna(0)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50.0
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50.0
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10.0
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20.0
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20.0
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40.0
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70.0
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110.0
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110.0
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90.0
10,101,0,0,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90,0.0
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90.0
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60.0
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60.0
14,105,David,0,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60.0
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60.0
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60.0
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100.0
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100.0
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100.0
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100.0
21,112,Jose Manuel,Urman,JMURMAN,0,07-MAR-06,FI_ACCOUNT,7800,-,108,100.0
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100.0
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30.0
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30.0
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30.0
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30.0
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30.0
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30.0
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50.0
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50.0
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50.0
32,123,Shanta,0,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,0.0
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50.0
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50.0
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50.0
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50.0
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50.0
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50.0
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50.0
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50.0
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50.0
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50.0
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50.0
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50.0
45,136,Hazel,0,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50.0
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50.0
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,0,50.0
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50.0
49,140,0,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50.0

In [10]:
df['NewFName']=df['FIRST_NAME'].fillna("Alex")
df.head(5)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,NewFName
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50.0,Donald
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50.0,Douglas
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10.0,Jennifer
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20.0,Michael
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20.0,Pat

In [11]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        2
LAST_NAME         4
EMAIL             0
PHONE_NUMBER      1
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        1
DEPARTMENT_ID     2
NewFName          0
dtype: int64

In [12]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,NewFName
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50.0,Donald
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50.0,Douglas
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10.0,Jennifer
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20.0,Michael
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20.0,Pat
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40.0,Susan
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70.0,Hermann
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110.0,Shelley
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110.0,William
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90.0,Steven
10,101,NaN,NaN,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90,NaN,Alex
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90.0,Lex
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60.0,Alexander
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60.0,Bruce
14,105,David,NaN,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60.0,David
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60.0,Valli
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60.0,Diana
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100.0,Nancy
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100.0,Daniel
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100.0,John
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100.0,Ismael
21,112,Jose Manuel,Urman,JMURMAN,NaN,07-MAR-06,FI_ACCOUNT,7800,-,108,100.0,Jose Manuel
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100.0,Luis
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30.0,Den
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30.0,Alexander
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30.0,Shelli
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30.0,Sigal
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30.0,Guy
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30.0,Karen
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50.0,Matthew
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50.0,Adam
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50.0,Payam
32,123,Shanta,NaN,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,NaN,Shanta
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50.0,Kevin
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50.0,Julia
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50.0,Irene
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50.0,James
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50.0,Steven
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50.0,Laura
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50.0,Mozhe
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50.0,James
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50.0,TJ
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50.0,Jason
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50.0,Michael
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50.0,Ki
45,136,Hazel,NaN,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50.0,Hazel
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50.0,Renske
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,NaN,50.0,Stephen
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50.0,John
49,140,NaN,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50.0,Alex

In [13]:
df.isnull().sum()
df['NewLName']=df['LAST_NAME'].fillna("Jaiswal")
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,NewFName,NewLName
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50.0,Donald,OConnell
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50.0,Douglas,Grant
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10.0,Jennifer,Whalen
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20.0,Michael,Hartstein
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20.0,Pat,Fay
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40.0,Susan,Mavris
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70.0,Hermann,Baer
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110.0,Shelley,Higgins
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110.0,William,Gietz
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90.0,Steven,King
10,101,NaN,NaN,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90,NaN,Alex,Jaiswal
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90.0,Lex,De Haan
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60.0,Alexander,Hunold
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60.0,Bruce,Ernst
14,105,David,NaN,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60.0,David,Jaiswal
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60.0,Valli,Pataballa
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60.0,Diana,Lorentz
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100.0,Nancy,Greenberg
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100.0,Daniel,Faviet
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100.0,John,Chen
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100.0,Ismael,Sciarra
21,112,Jose Manuel,Urman,JMURMAN,NaN,07-MAR-06,FI_ACCOUNT,7800,-,108,100.0,Jose Manuel,Urman
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100.0,Luis,Popp
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30.0,Den,Raphaely
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30.0,Alexander,Khoo
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30.0,Shelli,Baida
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30.0,Sigal,Tobias
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30.0,Guy,Himuro
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30.0,Karen,Colmenares
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50.0,Matthew,Weiss
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50.0,Adam,Fripp
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50.0,Payam,Kaufling
32,123,Shanta,NaN,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,NaN,Shanta,Jaiswal
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50.0,Kevin,Mourgos
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50.0,Julia,Nayer
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50.0,Irene,Mikkilineni
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50.0,James,Landry
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50.0,Steven,Markle
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50.0,Laura,Bissot
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50.0,Mozhe,Atkinson
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50.0,James,Marlow
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50.0,TJ,Olson
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50.0,Jason,Mallin
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50.0,Michael,Rogers
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50.0,Ki,Gee
45,136,Hazel,NaN,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50.0,Hazel,Jaiswal
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50.0,Renske,Ladwig
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,NaN,50.0,Stephen,Stiles
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50.0,John,Seo
49,140,NaN,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50.0,Alex,Patel

In [14]:
#Renaming Column
df=df.rename(columns={'HIRE_DATE':'JOINED_Date'})
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,JOINED_Date,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,NewFName,NewLName
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50.0,Donald,OConnell
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50.0,Douglas,Grant
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10.0,Jennifer,Whalen
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20.0,Michael,Hartstein
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20.0,Pat,Fay
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40.0,Susan,Mavris
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70.0,Hermann,Baer
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110.0,Shelley,Higgins
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110.0,William,Gietz
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90.0,Steven,King
10,101,NaN,NaN,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90,NaN,Alex,Jaiswal
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90.0,Lex,De Haan
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60.0,Alexander,Hunold
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60.0,Bruce,Ernst
14,105,David,NaN,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60.0,David,Jaiswal
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60.0,Valli,Pataballa
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60.0,Diana,Lorentz
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100.0,Nancy,Greenberg
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100.0,Daniel,Faviet
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100.0,John,Chen
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100.0,Ismael,Sciarra
21,112,Jose Manuel,Urman,JMURMAN,NaN,07-MAR-06,FI_ACCOUNT,7800,-,108,100.0,Jose Manuel,Urman
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100.0,Luis,Popp
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30.0,Den,Raphaely
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30.0,Alexander,Khoo
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30.0,Shelli,Baida
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30.0,Sigal,Tobias
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30.0,Guy,Himuro
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30.0,Karen,Colmenares
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50.0,Matthew,Weiss
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50.0,Adam,Fripp
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50.0,Payam,Kaufling
32,123,Shanta,NaN,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,NaN,Shanta,Jaiswal
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50.0,Kevin,Mourgos
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50.0,Julia,Nayer
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50.0,Irene,Mikkilineni
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50.0,James,Landry
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50.0,Steven,Markle
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50.0,Laura,Bissot
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50.0,Mozhe,Atkinson
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50.0,James,Marlow
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50.0,TJ,Olson
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50.0,Jason,Mallin
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50.0,Michael,Rogers
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50.0,Ki,Gee
45,136,Hazel,NaN,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50.0,Hazel,Jaiswal
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50.0,Renske,Ladwig
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,NaN,50.0,Stephen,Stiles
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50.0,John,Seo
49,140,NaN,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50.0,Alex,Patel