In [251]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [252]:
df=sns.load_dataset('tips')

In [253]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [254]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [255]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

# feature encoding

In [256]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [257]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [258]:
#independent and dependent feature
x=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y=df[['total_bill']]

In [259]:
#train test split
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=10)

In [260]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
xtrain['sex']=le1.fit_transform(xtrain['sex'])
xtrain['smoker']=le2.fit_transform(xtrain['smoker'])
xtrain['time']=le3.fit_transform(xtrain['time'])

In [261]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [262]:
xtrain.head()

      tip  sex  smoker   day  time  size
39   5.00    1       0   Sat     0     3
87   4.00    1       0  Thur     1     2
169  2.00    0       1   Sat     0     2
232  3.39    1       0   Sat     0     2
144  2.30    0       0  Thur     1     2

In [263]:
from sklearn.preprocessing import LabelEncoder
xtest['sex']=le1.transform(xtest['sex'])
xtest['smoker']=le2.transform(xtest['smoker'])
xtest['time']=le3.transform(xtest['time'])

In [264]:
from sklearn.preprocessing import OneHotEncoder

In [265]:
encoder=OneHotEncoder()
e=encoder.fit_transform(xtrain[['day']]).toarray()
e_df=pd.DataFrame(e,columns=encoder.get_feature_names_out())
e_df.head()

   day_Fri  day_Sat  day_Sun  day_Thur
0      0.0      1.0      0.0       0.0
1      0.0      0.0      0.0       1.0
2      0.0      1.0      0.0       0.0
3      0.0      1.0      0.0       0.0
4      0.0      0.0      0.0       1.0

In [266]:
encoder = OneHotEncoder()
e = encoder.fit_transform(xtrain[['day']]).toarray()
e_df = pd.DataFrame(e, columns=encoder.get_feature_names_out(), index=xtrain.index)

# correct concatenation (keep same row index)
xtrain = pd.concat([xtrain, e_df], axis=1)

xtrain.head()

      tip  sex  smoker   day  time  size  day_Fri  day_Sat  day_Sun  day_Thur
39   5.00    1       0   Sat     0     3      0.0      1.0      0.0       0.0
87   4.00    1       0  Thur     1     2      0.0      0.0      0.0       1.0
169  2.00    0       1   Sat     0     2      0.0      1.0      0.0       0.0
232  3.39    1       0   Sat     0     2      0.0      1.0      0.0       0.0
144  2.30    0       0  Thur     1     2      0.0      0.0      0.0       1.0

In [267]:
encoder = OneHotEncoder()
e = encoder.fit_transform(xtest[['day']]).toarray()
e_df = pd.DataFrame(e, columns=encoder.get_feature_names_out(), index=xtest.index)

# correct concatenation (keep same row index)
xtest = pd.concat([xtest, e_df], axis=1)

xtest.head()

      tip  sex  smoker  day  time  size  day_Fri  day_Sat  day_Sun  day_Thur
162  2.00    0       0  Sun     0     3      0.0      0.0      1.0       0.0
60   3.21    1       1  Sat     0     2      0.0      1.0      0.0       0.0
61   2.00    1       1  Sat     0     2      0.0      1.0      0.0       0.0
63   3.76    1       1  Sat     0     4      0.0      1.0      0.0       0.0
69   2.09    1       1  Sat     0     2      0.0      1.0      0.0       0.0

In [268]:
xtest.drop(columns='day',axis=-1,inplace=True)
xtest.head()

      tip  sex  smoker  time  size  day_Fri  day_Sat  day_Sun  day_Thur
162  2.00    0       0     0     3      0.0      0.0      1.0       0.0
60   3.21    1       1     0     2      0.0      1.0      0.0       0.0
61   2.00    1       1     0     2      0.0      1.0      0.0       0.0
63   3.76    1       1     0     4      0.0      1.0      0.0       0.0
69   2.09    1       1     0     2      0.0      1.0      0.0       0.0

In [269]:
xtrain.drop(columns='day',axis=-1,inplace=True)
xtrain.head()

      tip  sex  smoker  time  size  day_Fri  day_Sat  day_Sun  day_Thur
39   5.00    1       0     0     3      0.0      1.0      0.0       0.0
87   4.00    1       0     1     2      0.0      0.0      0.0       1.0
169  2.00    0       1     0     2      0.0      1.0      0.0       0.0
232  3.39    1       0     0     2      0.0      1.0      0.0       0.0
144  2.30    0       0     1     2      0.0      0.0      0.0       1.0

In [270]:
from sklearn.svm import SVR
s=SVR()
s.fit(xtrain,ytrain)

c:\Users\KIIT0001\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [271]:
y_pred=s.predict(xtest)

In [272]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(ytest,y_pred))
print(mean_absolute_error(ytest,y_pred))

0.42978079379995393
4.567603532654638