Label encoding is a technique used in machine learning and data preprocessing to convert categorical labels into a numerical format. This is particularly useful when working with algorithms that require numerical input. Each unique category is assigned a unique integer value.

In [3]:
import pandas as pd

In [6]:
df=pd.DataFrame({
    "color" : ['red','blue','green','blue']
})
df

   color
0    red
1   blue
2  green
3   blue

In [7]:
from sklearn.preprocessing import LabelEncoder

In [15]:
encoder=LabelEncoder()
encoded=encoder.fit_transform(df[['color']])
encoded

c:\Users\KIIT0001\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 0])

In [20]:
encoder.transform([['green']])

c:\Users\KIIT0001\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

# Ordinal Encoding

ordinal encoding is a method used to convert categorical variables with a meaningful order or ranking into numerical format. In ordinal encoding, each category is assigned an integer value based on its order or rank. This technique is useful when the categories have a natural hierarchy, such as "low," "medium," and "high." eg: 'cold', 'warm', 'hot'

In [22]:
df=pd.DataFrame({
    'education':['+2','master','schooling','bachelor']
})
df

   education
0         +2
1     master
2  schooling
3   bachelor

In [30]:
from sklearn.preprocessing import OrdinalEncoder

encoder=OrdinalEncoder(categories=[['schooling','+2','bachelor','master']])
encoded=encoder.fit_transform(df[['education']])
encoded=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoded

   education
0        1.0
1        3.0
2        0.0
3        2.0

In [31]:
pd.concat([df,encoded],axis=1)

   education  education
0         +2        1.0
1     master        3.0
2  schooling        0.0
3   bachelor        2.0